name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  mirror:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - macos-13

    permissions:
      contents: write

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_AUTO_UPDATE: '1'
      SKIP_POST: '1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Homebrew install
        if: startsWith('macos', matrix.os)
        uses: Homebrew/actions/setup-homebrew@master

      - name: Setup macos tools
        if: startsWith('macos', matrix.os)
        run: |
          brew --version

      - name: Build
        run: |
          ./scripts/setup.bash

      - name: Check linux
        if: startsWith('ubuntu', matrix.os)
        run: |
          which -a emacs

      - name: Release linux
        uses: softprops/action-gh-release@v2
        if: startsWith('ubuntu', matrix.os) && (github.event == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/'))
        with:
          generate_release_notes: true
          files: |
            ~/.local/bin/emacs
      
      - name: Release macos
        uses: softprops/action-gh-release@v2
        if: startsWith('macos', matrix.os) && (github.event == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/'))
        with:
          generate_release_notes: true
          files: |
            src/nextstep/Emacs.app

