name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  mirror:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - macos-13

    permissions:
      contents: write

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Build
        run: |
          ./scripts/setup.bash

      - name: Check
        run: |
          which -a emacs

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.event == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            ~/.local/bin/emacs

