name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - macos-13

    permissions:
      contents: write

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_AUTO_UPDATE: '1'
      SKIP_POST: '1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Homebrew install
        if: startsWith(matrix.os, 'macos')
        uses: Homebrew/actions/setup-homebrew@master

      - name: Setup macos tools
        if: startsWith(matrix.os, 'macos')
        run: |
          brew --version

      - name: Build
        run: |
          ./scripts/setup.bash

      - name: Archive [ubuntu]
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          tar -czvf ${{ github.workspace }}/emacs-${{ matrix.os }}.tar.gz \
            $(which emacs)
      
      - name: Archive [macos]
        if: startsWith(matrix.os, 'macos')
        run: |
          tar -czvf ${{ github.workspace }}/emacs-${{ matrix.os }}.tar.gz \
            ${{ github.workspace }}/src/nextstep/Emacs.app

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: emacs-${{ matrix.os }}
          path: ${{ github.workspace }}/emacs-${{ matrix.os }}.tar.gz

      - name: Release [ubuntu]
        uses: softprops/action-gh-release@v2
        if: startsWith(matrix.os, 'ubuntu') && startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            ~/.local/bin/emacs
      
      - name: Release [macos]
        uses: softprops/action-gh-release@v2
        if: startsWith(matrix.os, 'macos') && startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            src/nextstep/Emacs.app

